In [72]:
import time
import random
import warnings
warnings.filterwarnings("ignore")
from math import *
import operator
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", 10000)
import string
from pprint import pprint

# import plotting libraries
import matplotlib
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from matplotlib import style
%matplotlib inline 

import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)

# load make_blobs to simulate data
from sklearn.datasets import make_blobs
from sklearn.datasets import make_classification

# import the ML algorithm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier
from sklearn.cluster import KMeans
import xgboost as xgb
from xgboost import XGBClassifier
from xgboost import plot_importance
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import graphviz
from IPython.display import display

# import libraries for model validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold 

# import libraries for metrics and reporting
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import adjusted_rand_score
from sklearn.model_selection import GridSearchCV
from statsmodels.stats.outliers_influence import variance_inflation_factor
from scipy.stats import pearsonr
import statistics

In [102]:
train = pd.read_csv(r'C:\Users\Karan Mehta\Desktop\Hackathon\Kaggle competition\train.csv')

In [115]:
test = pd.read_csv(r'C:\Users\Karan Mehta\Desktop\Hackathon\Kaggle competition\test.csv')

In [75]:
train.isnull().sum()

id            0
feature_0     0
feature_1     0
feature_2     0
feature_3     0
feature_4     0
feature_5     0
feature_6     0
feature_7     0
feature_8     0
feature_9     0
feature_10    0
feature_11    0
feature_12    0
feature_13    0
feature_14    0
feature_15    0
feature_16    0
feature_17    0
feature_18    0
feature_19    0
feature_20    0
feature_21    0
feature_22    0
feature_23    0
feature_24    0
feature_25    0
feature_26    0
feature_27    0
feature_28    0
feature_29    0
feature_30    0
feature_31    0
feature_32    0
feature_33    0
feature_34    0
feature_35    0
feature_36    0
feature_37    0
feature_38    0
feature_39    0
feature_40    0
feature_41    0
feature_42    0
feature_43    0
feature_44    0
feature_45    0
feature_46    0
feature_47    0
feature_48    0
feature_49    0
target        0
dtype: int64

In [76]:
train.head()

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0,0,21,0,0,0,0,0,0,Class_2
1,1,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,3,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
2,2,0,0,0,0,0,0,0,0,0,2,0,0,1,0,1,0,0,0,0,1,0,5,2,1,1,0,1,0,2,0,0,0,0,19,2,0,1,7,3,0,0,0,1,0,0,0,0,13,2,0,Class_1
3,3,0,0,0,0,0,0,0,3,0,0,0,0,0,1,7,11,1,0,3,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,1,0,Class_4
4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,9,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,Class_2

In [77]:
''''corr = train.corr()
#print(corr)
plt.figure(figsize=(20,10))
sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns)'''

"'corr = train.corr()\n#print(corr)\nplt.figure(figsize=(20,10))\nsns.heatmap(corr, \n        xticklabels=corr.columns,\n        yticklabels=corr.columns)"

In [78]:
train.describe()

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.00000
mean,49999.500000,0.257830,0.431720,0.114130,0.590550,0.599770,0.160820,0.731490,1.228920,0.903350,0.940120,0.313680,0.403750,0.461470,0.07565,2.597320,1.242030,0.364830,0.740000,0.471220,1.564780,0.242890,0.661970,0.184740,0.388040,1.04013,0.408630,0.353550,0.300680,1.106060,0.169600,0.294500,1.372040,0.277510,0.612460,1.122150,0.908980,0.116530,0.398310,2.997170,0.674640,0.712270,0.582070,0.529230,0.616310,0.135100,0.358660,0.516810,0.39004,0.970850,0.55712
std,28867.657797,0.929033,1.977862,0.519584,1.844558,2.785531,0.601149,2.343465,2.692732,3.415258,1.904172,1.121168,1.011418,1.128729,0.35901,4.655092,2.160111,1.284152,1.819388,1.096423,4.749449,0.927461,2.182703,0.553854,1.215796,2.53991,1.321669,1.491937,1.592092,1.879629,0.739582,1.352963,3.319325,1.460705,2.283595,2.493045,2.952305,0.411014,1.095268,5.386551,3.732428,1.721863,2.003114,2.300826,2.360955,0.627592,1.464187,2.171415,1.48735,2.576615,1.68093
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-2.000000,0.000000,0.000000,-2.000000,0.000000,0.000000,-8.000000,-5.000000,0.000000,0.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
25%,24999.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
50%,49999.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
75%,74999.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,3.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.00000
max,99999.000000,10.000000,31.000000,6.000000,26.000000,38.000000,10.000000,27.000000,31.000000,39.000000,17.000000,16.000000,12.000000,11.000000,3.00000,51.000000,20.000000,19.000000,16.000000,13.000000,55.000000,17.000000,36.000000,4.000000,19.000000,34.00000,23.000000,21.000000,31.000000,23.000000,13.000000,41.000000,46.000000,27.000000,24.000000,25.000000,43.000000,3.000000,14.000000,66.000000,66.000000,21.000000,32.000000,37.000000,33.000000,9.000000,26.000000,29.000000,25.00000,44.000000,20.00000

In [79]:
train.shape

(100000, 52)

In [80]:
train['feature_0'].unique()

array([ 0,  1,  9,  2,  3,  4,  7,  5,  6,  8, 10], dtype=int64)

In [81]:
train[train['target']=='Class_2']#57497

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0,0,21,0,0,0,0,0,0,Class_2
4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,9,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,Class_2
5,5,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,Class_2
7,7,0,0,0,2,0,0,3,0,0,6,0,3,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,3,0,0,0,8,0,0,0,1,0,0,0,0,2,0,0,Class_2
8,8,0,1,0,0,0,0,0,0,15,0,0,0,0,0,0,3,0,0,1,0,0,7,0,4,0,0,0,0,12,1,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,Class_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,99991,0,0,0,1,0,1,0,1,0,2,0,0,0,0,0,2,0,1,0,0,0,1,0,13,1,0,0,0,0,0,0,0,0,1,4,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,Class_2
99992,99992,0,0,0,2,0,0,0,12,0,0,1,1,0,0,2,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5,0,0,0,0,4,0,0,0,0,2,0,0,0,0,0,Class_2
99993,99993,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,3,4,0,3,0,1,0,0,0,0,0,0,0,Class_2
99996,99996,0,0,0,0,0,0,0,1,2,0,0,0,0,0,4,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,3,0,1,0,0,0,7,0,0,0,2,0,0,0,10,0,0,0,Class_2
99998,99998,0,0,0,0,1,0,0,0,0,5,0,0,0,0,2,0,0,0,3,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,4,0,Class_2

In [82]:
train[train['target']=='Class_1']#8490

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
1,1,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,3,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
2,2,0,0,0,0,0,0,0,0,0,2,0,0,1,0,1,0,0,0,0,1,0,5,2,1,1,0,1,0,2,0,0,0,0,19,2,0,1,7,3,0,0,0,1,0,0,0,0,13,2,0,Class_1
6,6,0,0,0,1,0,0,0,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,8,0,3,0,0,3,1,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0,Class_1
15,15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,4,0,0,1,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
33,33,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,1,0,0,1,0,0,5,1,0,9,0,0,2,0,8,0,0,0,0,0,0,0,0,0,0,0,Class_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99939,99939,1,0,0,0,0,0,7,0,0,0,0,0,0,0,4,1,0,1,1,0,0,0,0,2,0,0,0,0,1,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,Class_1
99944,99944,0,0,0,0,0,0,2,0,3,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,5,3,0,0,0,0,0,1,0,1,0,0,0,8,0,0,1,0,0,3,0,0,0,0,0,0,Class_1
99949,99949,0,2,0,0,0,0,0,0,1,2,0,2,3,0,3,4,0,0,0,29,0,1,1,1,11,0,1,0,0,1,0,1,0,0,1,0,0,0,34,1,0,0,0,0,0,0,0,0,0,0,Class_1
99968,99968,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,1,0,0,0,5,2,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,1,2,Class_1
99995,99995,0,0,0,1,0,0,0,2,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,5,0,0,0,0,0,0,0,0,1,0,0,6,0,0,3,0,0,0,Class_1

In [83]:
train[train['target']=='Class_3']#21420

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
12,12,0,0,0,0,4,0,7,0,0,0,0,0,1,1,2,0,4,0,2,0,0,0,0,0,10,0,0,0,0,0,0,3,0,0,4,0,0,0,0,0,0,1,12,0,0,1,0,0,0,3,Class_3
14,14,9,0,0,1,0,0,0,0,0,0,2,1,0,0,0,5,2,0,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,2,0,0,2,0,0,0,0,3,0,Class_3
16,16,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,5,0,2,0,0,0,0,1,0,1,0,1,0,1,0,0,7,0,0,1,0,0,1,13,0,0,1,0,0,0,0,0,0,2,0,Class_3
21,21,0,0,0,0,0,0,0,0,0,0,0,0,3,0,3,0,0,0,0,0,2,0,0,2,0,0,0,0,6,0,0,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0,1,0,7,0,Class_3
29,29,0,0,0,1,0,0,0,0,2,0,0,0,2,0,0,4,0,0,0,10,0,0,2,0,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,2,1,0,1,Class_3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99983,99983,0,0,0,7,0,2,0,18,0,0,0,0,0,1,5,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,16,0,0,0,0,0,0,6,0,0,1,0,0,0,0,0,0,0,0,Class_3
99988,99988,0,0,0,2,0,0,8,0,3,1,0,0,0,0,0,2,0,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,3,13,0,27,0,0,3,10,5,0,0,0,0,1,0,0,0,0,Class_3
99994,99994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,1,4,1,0,0,0,0,0,5,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,Class_3
99997,99997,0,0,0,0,0,1,0,0,0,4,0,0,3,0,0,0,0,0,0,1,0,0,0,3,0,0,0,0,4,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,1,0,0,2,0,Class_3
99999,99999,0,0,0,0,0,0,0,0,0,3,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,7,11,0,0,5,0,0,0,1,0,0,8,Class_3

In [84]:
train[train['target']=='Class_4']#12593

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,target
3,3,0,0,0,0,0,0,0,3,0,0,0,0,0,1,7,11,1,0,3,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,1,0,Class_4
9,9,0,0,1,0,0,0,0,0,1,1,0,0,2,0,0,1,0,0,0,0,0,1,0,0,1,2,0,0,3,0,0,0,0,0,1,0,0,1,6,0,2,1,0,0,0,0,0,0,1,0,Class_4
11,11,1,0,0,0,0,0,2,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,1,0,0,0,0,0,0,0,1,2,0,Class_4
13,13,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,3,0,0,1,0,0,1,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,Class_4
25,25,0,2,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,0,0,2,0,0,0,0,0,2,0,0,0,0,3,0,0,1,0,0,0,0,0,0,4,Class_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99951,99951,1,0,0,0,0,0,0,1,0,12,0,1,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,1,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,Class_4
99956,99956,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,2,0,2,1,0,0,5,0,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,Class_4
99972,99972,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Class_4
99974,99974,0,0,0,1,4,1,0,3,4,0,0,0,0,0,0,6,2,5,0,3,0,0,0,0,0,0,1,0,1,0,0,3,0,0,0,3,0,0,3,0,0,4,0,0,0,0,0,0,0,0,Class_4
99975,99975,5,0,0,0,0,0,0,0,0,1,4,0,0,0,40,0,6,1,2,9,0,1,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,0,6,0,0,0,0,0,0,1,0,0,0,1,Class_4

In [85]:
'''sns.set_theme(style='ticks')
#df = sns.load_dataset("Wages")
sns.pairplot(train , hue = 'target')'''

'sns.set_theme(style=\'ticks\')\n#df = sns.load_dataset("Wages")\nsns.pairplot(train , hue = \'target\')'

In [86]:
train.columns

Index(['id', 'feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49',
       'target'],
      dtype='object')

In [87]:
#(train<0).any()

In [88]:
'''train['total'] = train['feature_0' + 'feature_1'+ 'feature_2'+ 'feature_3'+ 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49'])
'''

"train['total'] = train['feature_0' + 'feature_1'+ 'feature_2'+ 'feature_3'+ 'feature_4',\n       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',\n       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',\n       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',\n       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',\n       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',\n       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',\n       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',\n       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',\n       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49'])\n"

In [89]:
train['total'] = train.values[:,1:49].sum(axis =1)

In [90]:
train.groupby(by=['target'])['total'].unique()

target
Class_1    [11, 63, 38, 9, 34, 29, 24, 27, 33, 6, 35, 23,...
Class_2    [34, 16, 5, 35, 47, 41, 84, 28, 72, 50, 54, 45...
Class_3    [52, 29, 38, 21, 30, 25, 47, 33, 35, 45, 37, 6...
Class_4    [34, 24, 10, 18, 17, 13, 16, 45, 11, 30, 44, 3...
Name: total, dtype: object

In [91]:
train.groupby(by=['target'])['total'].describe()

         count  unique  top  freq
target
Class_1   8490     109   25   252
Class_2  57497     125   22  1615
Class_3  21420     120   21   591
Class_4  12593     110   20   395

In [92]:
feature_names = ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49']

In [93]:
X = train[feature_names]
y = train['target']

In [94]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler = MinMaxScaler()
X_std = scaler.fit_transform(X)

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X_std,y,test_size=0.2,random_state=0)

# Logistics regression

In [25]:
clf = LogisticRegression(random_state=0, multi_class='ovr')

In [26]:
model = clf.fit(X_train, y_train)

In [27]:
X_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.03225806, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.04545455,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08      , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [28]:
y_test

3582     Class_4
60498    Class_4
53227    Class_3
21333    Class_2
3885     Class_3
          ...
60116    Class_2
2415     Class_2
43763    Class_2
71345    Class_2
77687    Class_3
Name: target, Length: 20000, dtype: object

In [29]:
y

0        Class_2
1        Class_1
2        Class_1
3        Class_4
4        Class_2
          ...
99995    Class_1
99996    Class_2
99997    Class_3
99998    Class_2
99999    Class_3
Name: target, Length: 100000, dtype: object

In [30]:
z_pred=model.predict(X_test)

In [31]:
z= model.predict_proba(X_test)
z[0:5]

array([[0.0867854 , 0.54121345, 0.25746862, 0.11453252],
       [0.07509757, 0.60435928, 0.20584374, 0.1146994 ],
       [0.07229034, 0.56577519, 0.23163204, 0.13030242],
       [0.07695009, 0.54828914, 0.22034166, 0.15441911],
       [0.07608059, 0.62498509, 0.20715299, 0.09178132]])

In [32]:
from sklearn.metrics import f1_score
LR_f1 = f1_score(y_test, z_pred, average='weighted')
print(LR_f1)

0.4206699497513721

In [34]:
from sklearn.metrics import log_loss
LR_log = log_loss(y_test, z)
print(LR_log)

1.109398491270362

In [116]:
test_id = test.id

In [117]:
del test['id']

In [37]:
#scaler = StandardScaler()
test_std = scaler.fit_transform(test)

In [38]:
test_pred=model.predict(test_std)

In [39]:
test_proba= model.predict_proba(test_std)

In [40]:
test_proba[0:5]

array([[0.08733031, 0.62968465, 0.18070037, 0.10228467],
       [0.0982538 , 0.58403309, 0.20411016, 0.11360295],
       [0.08645129, 0.631715  , 0.17674898, 0.10508473],
       [0.08545846, 0.52807281, 0.29907034, 0.08739839],
       [0.07416068, 0.59420371, 0.19563675, 0.13599886]])

In [41]:
'''submission = pd.DataFrame(test_proba, columns=['Class_1','Class_2','Class_3','Class_4'])
submission['id'] = test_id
submission'''

"submission = pd.DataFrame(test_proba, columns=['Class_1','Class_2','Class_3','Class_4'])\nsubmission['id'] = test_id\nsubmission"

In [42]:
#submission.to_csv("Final_submission.csv",index=False)

# Gradient boosting

In [43]:
model_GB = GradientBoostingClassifier()
model_GB.fit(X_train, y_train)
predictions=model_GB.predict(X_test)

In [44]:
z_pred_GB=model_GB.predict(X_test)

In [45]:
z_GB= model_GB.predict_proba(X_test)

In [46]:
z_GB[0:5]

array([[0.07889244, 0.59059491, 0.23724788, 0.09326477],
       [0.0813293 , 0.60515497, 0.21689921, 0.09661652],
       [0.07995363, 0.48850732, 0.31978478, 0.11175427],
       [0.07538411, 0.59390563, 0.17573784, 0.15497242],
       [0.08594078, 0.57847498, 0.22862591, 0.10695833]])

In [47]:
LR_log = log_loss(y_test, z_GB)
print(LR_log)

1.10009941214479

In [48]:
test_pred=model_GB.predict(test_std)

In [49]:
test_proba= model_GB.predict_proba(test_std)

In [50]:
''''submission = pd.DataFrame(test_proba, columns=['Class_1','Class_2','Class_3','Class_4'])
submission['id'] = test_id
submission'''

"'submission = pd.DataFrame(test_proba, columns=['Class_1','Class_2','Class_3','Class_4'])\nsubmission['id'] = test_id\nsubmission"

In [51]:
#submission.to_csv("Final_submission.csv",index=False)

# ADA Boosting

In [52]:
def ada_boost(X_train, X_test, y_train, y_test):
    model_AB = AdaBoostClassifier(learning_rate = 0.5, n_estimators=500)
    model_AB.fit(X_train, y_train)
    # predict class labels for the test set (Churn = True, Not Churn = False)
    predicted = model_AB.predict(X_test)
    # generate class probabilities
    z_AB = model_AB.predict_proba(X_test)
    return model_AB, predicted, z_AB

In [53]:
model_AB, predicted, z_AB = ada_boost(X_train, X_test, y_train, y_test)

In [54]:
LR_log = log_loss(y_test, z_AB)
print(LR_log)

1.3838605039551564

In [58]:
from sklearn.linear_model import SGDClassifier

In [66]:
 SD = SGDClassifier(loss="log", penalty="l2", max_iter=5)

In [67]:
SD.fit(X_train, y_train)

SGDClassifier(loss='log', max_iter=5)

In [69]:
z_SD= SD.predict_proba(X_test)

In [70]:
LR_log = log_loss(y_test, z_SD)
print(LR_log)

1.109900844131698

In [67]:
''''from sklearn.linear_model import Ridge
 
# Train the model
ridgeR = Ridge(alpha = 1)
ridgeR.fit(X_train, y_train)
y_pred = ridgeR.predict(X_test)'''

"'from sklearn.linear_model import Ridge\n \n# Train the model\nridgeR = Ridge(alpha = 1)\nridgeR.fit(X_train, y_train)\ny_pred = ridgeR.predict(X_test)"

In [25]:
import keras 

from keras.models import Sequential

from keras.layers import Dense, Dropout, Activation

from keras.optimizers import SGD,Adam

from keras.metrics import categorical_accuracy

In [32]:
X_train.shape

(80000, 50)

In [33]:
y_train.shape

(80000,)

In [34]:
data_tr = pd.get_dummies(data=train, columns=['target'])

In [40]:
data_tr.columns

Index(['id', 'feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49',
       'total', 'target_Class_1', 'target_Class_2', 'target_Class_3',
       'target_Class_4'],
      dtype='object')

In [41]:
traget = [ 'target_Class_1', 'target_Class_2', 'target_Class_3',
       'target_Class_4']

In [43]:
X = train[feature_names]
y = data_tr[traget]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X_std,y,test_size=0.2,random_state=0)

In [50]:
model = Sequential()

model.add(Dense(64,activation='relu',input_dim=50))

model.add(Dropout(0.5))

model.add(Dense(512,activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(4,activation='softmax'))

In [57]:
model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [66]:
model.fit(X_train,y_train, epochs=250, batch_size=256,shuffle=True)

Epoch 1/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0968 - accuracy: 0.5818
Epoch 2/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0968 - accuracy: 0.5818
Epoch 3/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0955 - accuracy: 0.5817
Epoch 4/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0961 - accuracy: 0.5819
Epoch 5/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0961 - accuracy: 0.5816
Epoch 6/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0962 - accuracy: 0.5813
Epoch 7/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0954 - accuracy: 0.5825
Epoch 8/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0964 - accuracy: 0.5814
Epoch 9/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0960 - accuracy: 0.5821
Epoch 10/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0954 - accuracy: 0.5822
Epoch 11/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0961 - accuracy: 0.5820
Epoch 12/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0958 - accuracy: 0.5814
Epoch 13/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0959 - accuracy: 0.5821
Epoch 14/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0956 - accuracy: 0.5815
Epoch 15/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0958 - accuracy: 0.5819
Epoch 16/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0959 - accuracy: 0.5821
Epoch 17/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0966 - accuracy: 0.5817
Epoch 18/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0952 - accuracy: 0.5822
Epoch 19/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0958 - accuracy: 0.5817
Epoch 20/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0957 - accuracy: 0.5823
Epoch 21/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5821
Epoch 22/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0948 - accuracy: 0.5824
Epoch 23/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0962 - accuracy: 0.5818
Epoch 24/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0957 - accuracy: 0.5820
Epoch 25/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0961 - accuracy: 0.5817
Epoch 26/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0956 - accuracy: 0.5822
Epoch 27/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5824
Epoch 28/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0958 - accuracy: 0.5816
Epoch 29/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5818
Epoch 30/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0954 - accuracy: 0.5817
Epoch 31/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0953 - accuracy: 0.5822
Epoch 32/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5832
Epoch 33/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5824
Epoch 34/250
313/313 [==============================] - 2s 5ms/step - loss: 1.0958 - accuracy: 0.5819
Epoch 35/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0955 - accuracy: 0.5816
Epoch 36/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0955 - accuracy: 0.5820
Epoch 37/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0954 - accuracy: 0.5821
Epoch 38/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0953 - accuracy: 0.5826
Epoch 39/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0958 - accuracy: 0.5819
Epoch 40/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0951 - accuracy: 0.5822
Epoch 41/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0955 - accuracy: 0.5821
Epoch 42/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5814
Epoch 43/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0944 - accuracy: 0.5825
Epoch 44/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0944 - accuracy: 0.5822
Epoch 45/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5821
Epoch 46/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0957 - accuracy: 0.5819
Epoch 47/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0952 - accuracy: 0.5822
Epoch 48/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5825
Epoch 49/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0948 - accuracy: 0.5823
Epoch 50/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5827
Epoch 51/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5825
Epoch 52/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0941 - accuracy: 0.5831
Epoch 53/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0952 - accuracy: 0.5829
Epoch 54/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5823
Epoch 55/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5825
Epoch 56/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5827
Epoch 57/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5832
Epoch 58/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5830
Epoch 59/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5828
Epoch 60/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5827
Epoch 61/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5821
Epoch 62/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0950 - accuracy: 0.5825
Epoch 63/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5824
Epoch 64/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0944 - accuracy: 0.5827
Epoch 65/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5833
Epoch 66/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5829
Epoch 67/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5827
Epoch 68/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0942 - accuracy: 0.5825
Epoch 69/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0953 - accuracy: 0.5821
Epoch 70/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0941 - accuracy: 0.5824
Epoch 71/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0940 - accuracy: 0.5831
Epoch 72/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0954 - accuracy: 0.5828
Epoch 73/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0942 - accuracy: 0.5825
Epoch 74/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0952 - accuracy: 0.5824
Epoch 75/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5829
Epoch 76/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5833
Epoch 77/250
313/313 [==============================] - 2s 5ms/step - loss: 1.0937 - accuracy: 0.5830
Epoch 78/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5827
Epoch 79/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5831
Epoch 80/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5827
Epoch 81/250

313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5832
Epoch 82/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5830
Epoch 83/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5830
Epoch 84/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0936 - accuracy: 0.5834
Epoch 85/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5829
Epoch 86/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5837
Epoch 87/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0946 - accuracy: 0.5830
Epoch 88/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5829
Epoch 89/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0947 - accuracy: 0.5824
Epoch 90/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0940 - accuracy: 0.5829
Epoch 91/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0940 - accuracy: 0.5829
Epoch 92/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0941 - accuracy: 0.5827
Epoch 93/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5832
Epoch 94/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5837
Epoch 95/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0937 - accuracy: 0.5832
Epoch 96/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5825
Epoch 97/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5833
Epoch 98/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0942 - accuracy: 0.5832
Epoch 99/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5830
Epoch 100/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5831
Epoch 101/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5827
Epoch 102/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0941 - accuracy: 0.5828
Epoch 103/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5823
Epoch 104/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0945 - accuracy: 0.5830
Epoch 105/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5825
Epoch 106/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5836
Epoch 107/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5832
Epoch 108/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5829
Epoch 109/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0936 - accuracy: 0.5830
Epoch 110/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5829
Epoch 111/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5828
Epoch 112/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0939 - accuracy: 0.5828
Epoch 113/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5828
Epoch 114/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0943 - accuracy: 0.5827
Epoch 115/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5826
Epoch 116/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0928 - accuracy: 0.5827
Epoch 117/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5829
Epoch 118/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5835
Epoch 119/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5840
Epoch 120/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5836
Epoch 121/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5834
Epoch 122/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5835
Epoch 123/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0929 - accuracy: 0.5837
Epoch 124/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0929 - accuracy: 0.5839
Epoch 125/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0931 - accuracy: 0.5832
Epoch 126/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5836
Epoch 127/250
313/313 [==============================] - 1s 5ms/step - loss: 1.0930 - accuracy: 0.5833
Epoch 128/250
313/313 [==============================] - 1s 5ms/step - loss: 1.0926 - accuracy: 0.5835
Epoch 129/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0936 - accuracy: 0.5837
Epoch 130/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5838
Epoch 131/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0928 - accuracy: 0.5836
Epoch 132/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5835
Epoch 133/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5836
Epoch 134/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0928 - accuracy: 0.5829
Epoch 135/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5829
Epoch 136/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5839
Epoch 137/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5831
Epoch 138/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5834
Epoch 139/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5838
Epoch 140/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5835
Epoch 141/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0941 - accuracy: 0.5831
Epoch 142/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5839
Epoch 143/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5833
Epoch 144/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0940 - accuracy: 0.5834
Epoch 145/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5838
Epoch 146/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5831
Epoch 147/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5836
Epoch 148/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0938 - accuracy: 0.5829
Epoch 149/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0931 - accuracy: 0.5831
Epoch 150/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5832
Epoch 151/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5839
Epoch 152/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5838
Epoch 153/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0929 - accuracy: 0.5828
Epoch 154/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5838
Epoch 155/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5837
Epoch 156/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5836
Epoch 157/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0927 - accuracy: 0.5834
Epoch 158/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0933 - accuracy: 0.5838
Epoch 159/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5836
Epoch 160/250

313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5840
Epoch 161/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5833
Epoch 162/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5847
Epoch 163/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5840
Epoch 164/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5840
Epoch 165/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5836
Epoch 166/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5836
Epoch 167/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5834
Epoch 168/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5834
Epoch 169/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0928 - accuracy: 0.5841
Epoch 170/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5838
Epoch 171/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5836
Epoch 172/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0927 - accuracy: 0.5834
Epoch 173/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5840
Epoch 174/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5838
Epoch 175/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0911 - accuracy: 0.5842
Epoch 176/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0934 - accuracy: 0.5830
Epoch 177/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0922 - accuracy: 0.5837
Epoch 178/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0914 - accuracy: 0.5845
Epoch 179/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5839
Epoch 180/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5836
Epoch 181/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5838
Epoch 182/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0916 - accuracy: 0.5840
Epoch 183/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0918 - accuracy: 0.5837
Epoch 184/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5834
Epoch 185/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0935 - accuracy: 0.5832
Epoch 186/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5836
Epoch 187/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5838
Epoch 188/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0922 - accuracy: 0.5836
Epoch 189/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5838
Epoch 190/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0927 - accuracy: 0.5839
Epoch 191/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0914 - accuracy: 0.5841
Epoch 192/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5835
Epoch 193/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5838
Epoch 194/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5837
Epoch 195/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0910 - accuracy: 0.5842
Epoch 196/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0930 - accuracy: 0.5836
Epoch 197/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5840
Epoch 198/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5835
Epoch 199/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0920 - accuracy: 0.5838
Epoch 200/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0927 - accuracy: 0.5837
Epoch 201/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5838
Epoch 202/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0913 - accuracy: 0.5845
Epoch 203/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5836
Epoch 204/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5836
Epoch 205/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5837
Epoch 206/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0928 - accuracy: 0.5834
Epoch 207/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5840
Epoch 208/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5839
Epoch 209/250
313/313 [==============================] - 2s 5ms/step - loss: 1.0919 - accuracy: 0.5839: 0s - loss: 1.0910
Epoch 210/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0917 - accuracy: 0.5838
Epoch 211/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0926 - accuracy: 0.5838
Epoch 212/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0922 - accuracy: 0.5842
Epoch 213/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5840
Epoch 214/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0916 - accuracy: 0.5844
Epoch 215/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0918 - accuracy: 0.5840
Epoch 216/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0916 - accuracy: 0.5843
Epoch 217/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0931 - accuracy: 0.5840
Epoch 218/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0917 - accuracy: 0.5839
Epoch 219/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5836
Epoch 220/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5844
Epoch 221/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0922 - accuracy: 0.5838
Epoch 222/250
313/313 [==============================] - 1s 5ms/step - loss: 1.0910 - accuracy: 0.5844
Epoch 223/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0917 - accuracy: 0.5840
Epoch 224/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0913 - accuracy: 0.5839
Epoch 225/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0915 - accuracy: 0.5839
Epoch 226/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0911 - accuracy: 0.5846
Epoch 227/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0913 - accuracy: 0.5838
Epoch 228/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0910 - accuracy: 0.5840
Epoch 229/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0927 - accuracy: 0.5838
Epoch 230/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0932 - accuracy: 0.5836
Epoch 231/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0921 - accuracy: 0.5842
Epoch 232/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0916 - accuracy: 0.5838
Epoch 233/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0922 - accuracy: 0.5835
Epoch 234/250
313/313 [==============================] - 2s 5ms/step - loss: 1.0918 - accuracy: 0.5839
Epoch 235/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0924 - accuracy: 0.5837
Epoch 236/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5843
Epoch 237/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0925 - accuracy: 0.5840
Epoch 238/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0918 - accuracy: 0.5839
Epoch 239/250

313/313 [==============================] - 1s 4ms/step - loss: 1.0914 - accuracy: 0.5838
Epoch 240/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0916 - accuracy: 0.5845
Epoch 241/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0910 - accuracy: 0.5837
Epoch 242/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0923 - accuracy: 0.5838
Epoch 243/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0917 - accuracy: 0.5840
Epoch 244/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5839
Epoch 245/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0918 - accuracy: 0.5841
Epoch 246/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0917 - accuracy: 0.5838
Epoch 247/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0919 - accuracy: 0.5839
Epoch 248/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0913 - accuracy: 0.5841
Epoch 249/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0918 - accuracy: 0.5837
Epoch 250/250
313/313 [==============================] - 1s 4ms/step - loss: 1.0908 - accuracy: 0.5843

In [68]:
z_NN= model.predict_proba(X_test)

In [70]:
from sklearn.metrics import log_loss
LR_log = log_loss(y_test, z_NN)
print(LR_log)

1.1821748881175882

In [96]:
model_NB = GaussianNB()
model_NB.fit(X_train,y_train)
predictions=model_NB.predict(X_test)

In [98]:
predictions.predict_proba(X_test)

AttributeError: 'numpy.ndarray' object has no attribute 'predict_proba'

In [99]:
model_XG = XGBClassifier()

In [100]:
model_XG.fit(X_train,y_train)
prediction=model_XG.predict(X_test)

[23:24:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [101]:
prediction.predict_proba(X_test)

AttributeError: 'numpy.ndarray' object has no attribute 'predict_proba'

In [60]:
#loss=LogLossFunction(X_train,y_train)

In [61]:
''''from hep_ml.gradientboosting import UGradientBoostingClassifier, LogLossFunction
classifier = UGradientBoostingClassifier(loss=LogLossFunction(), n_estimators=100)
classifier.fit(X_train,y_train)'''

"'from hep_ml.gradientboosting import UGradientBoostingClassifier, LogLossFunction\nclassifier = UGradientBoostingClassifier(loss=LogLossFunction(), n_estimators=100)\nclassifier.fit(X_train,y_train)"

In [62]:
''''from sklearn.model_selection import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import gc
from tqdm import *'''

"'from sklearn.model_selection import *\nfrom sklearn.preprocessing import *\nfrom sklearn.metrics import *\nfrom lightgbm import LGBMClassifier\nfrom catboost import CatBoostClassifier\n\nimport gc\nfrom tqdm import *"

In [ ]:
''''oofs = np.zeros((len(train), 4))
preds = np.zeros((len(test), 4))
N_SPLITS = 15
folds = StratifiedKFold(N_SPLITS, shuffle = True, random_state = 77)

for fold_, (trn_idx, val_idx) in enumerate(folds.split(train, train['target'])):

  print(f'\n\n Fold {fold_} \\n\n')
  X_trn, y_trn = train[feature_names].iloc[trn_idx], train["target"][trn_idx]
  X_val, y_val = train[feature_names].iloc[val_idx], train["target"][val_idx]

  clf = LGBMClassifier(n_estimators = 10000, learning_rate = 0.05, colsample_bytree = 0.5, reg_alpha = 0.5, reg_lambda = 1, random_state = 2)
  #clf = CatBoostClassifier(iterations = 5000, learning_rate = 0.06, random_state=2, reg_lambda=0.5, eval_metric='MultiClass', task_type = 'GPU')

  clf.fit(X_trn, y_trn, eval_set = [(X_val, y_val)], early_stopping_rounds = 150, verbose = 50)

  oofs[val_idx] = clf.predict_proba(X_val)
  preds += clf.predict_proba(test[feature_names]) / N_SPLITS'''

In [ ]:
'''from lightautoml.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML
from lightautoml.tasks import Task
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder'''

In [ ]:
'''N_THREADS = 4 # threads cnt for lgbm and linear models
N_FOLDS = 5 # folds cnt for AutoML
RANDOM_STATE = 2021 # fixed random state for various reasons
TEST_SIZE = 0.2 # Test size for metric check
TIMEOUT = 60 * 60'''

In [ ]:
'''le = LabelEncoder()
train['target'] = le.fit_transform(train['target'])'''

In [ ]:
'''%%time

automl = TabularUtilizedAutoML(task = Task('multiclass',), 
                               timeout = TIMEOUT,
                               cpu_limit = N_THREADS,
                               verbose=0,
                               reader_params = {'n_jobs': N_THREADS},
)'''

In [ ]:
'''target_column = 'target'

roles = {
    'target': target_column,
    'drop': ['id'],
}

lightml_pred = automl.fit_predict(train.iloc[:,:-1], roles = roles)
print('lightml_pred:\n{}\nShape = {}'.format(lightml_pred[:10], lightml_pred.shape))'''

In [ ]:
'''%%time

test_pred = automl.predict(test)
print('Prediction for test set:\n{}\nShape = {}'.format(test_pred[:5], test_pred.shape))'''

In [ ]:
'''sub.iloc[:, 1:] = test_pred.data
sub.to_csv('Submission1.csv', index = False)'''

In [105]:
from sklearn.preprocessing import (StandardScaler, PowerTransformer,
                                   QuantileTransformer ,LabelEncoder, 
                                   OneHotEncoder,OrdinalEncoder)

In [106]:
features = [f'feature_{i}' for i in range(50)]

target = train['target']
le = LabelEncoder()
target = le.fit_transform(target)

train = train[features].to_numpy()
test = test[features].to_numpy()

scaler = StandardScaler()
train = scaler.fit_transform(train)
test = scaler.transform(test)

In [120]:
nfolds = 5
seed = 43

# params = {
#  'objective':'multiclass',
#  'num_class':4,
#  'reg_alpha': 6.147694913504962,
#  'reg_lambda': 0.002457826062076097,
#  'colsample_bytree': 0.3,
#  'subsample': 0.8,
#  'learning_rate': 0.001,
#  'max_depth': 20,
#  'num_leaves': 111,
#  'min_child_samples': 285,
#  'random_state': 48,
# 'verbose':-1,
#  'n_estimators': 1600000,
# #  'n_estimators': 100,
#  'cat_smooth': 39}

params = {
 'objective':'multiclass',
 'num_class':4,
 'random_state': 150,
'verbose':-1,
 'n_estimators': 10000}

In [121]:
import lightgbm as lgb
from sklearn.model_selection import KFold, StratifiedKFold
lgbm_preds = np.zeros((test.shape[0],4))

kfold = StratifiedKFold(n_splits=nfolds,shuffle=True,random_state=seed)
lgbm_scores = list()
for k, (train_idx, valid_idx) in enumerate(kfold.split(X=train,y=target)):
    print(f"Fold: {k}")
    lgb_train = lgb.Dataset(train[train_idx],target[train_idx])
    lgb_valid = lgb.Dataset(train[valid_idx],target[valid_idx],reference=lgb_train)
    lgb_model = lgb.train(params,
                      lgb_train, 
                      valid_sets=[lgb_train,lgb_valid],
                      verbose_eval=1000,
                      early_stopping_rounds=800,
                      )
    lgbm_preds += lgb_model.predict(test)/nfolds

Fold: 0
Training until validation scores don't improve for 800 rounds
Early stopping, best iteration is:
[93]	training's multi_logloss: 1.04351	valid_1's multi_logloss: 1.09551
Fold: 1
Training until validation scores don't improve for 800 rounds
Early stopping, best iteration is:
[110]	training's multi_logloss: 1.03645	valid_1's multi_logloss: 1.09443
Fold: 2
Training until validation scores don't improve for 800 rounds
Early stopping, best iteration is:
[118]	training's multi_logloss: 1.03252	valid_1's multi_logloss: 1.09508
Fold: 3
Training until validation scores don't improve for 800 rounds
Early stopping, best iteration is:
[96]	training's multi_logloss: 1.04177	valid_1's multi_logloss: 1.09656
Fold: 4
Training until validation scores don't improve for 800 rounds
Early stopping, best iteration is:
[101]	training's multi_logloss: 1.03906	valid_1's multi_logloss: 1.09624

In [118]:
submission = pd.DataFrame(lgbm_preds, columns=['Class_1','Class_2','Class_3','Class_4'])
submission['id'] = test_id
submission

        Class_1   Class_2   Class_3   Class_4      id
0      0.081360  0.592732  0.203915  0.121992  100000
1      0.067314  0.678412  0.156414  0.097860  100001
2      0.086817  0.632084  0.177203  0.103896  100002
3      0.081236  0.541902  0.249443  0.127419  100003
4      0.073557  0.614599  0.212583  0.099261  100004
...         ...       ...       ...       ...     ...
49995  0.082227  0.680611  0.160165  0.076997  149995
49996  0.074986  0.660564  0.141357  0.123094  149996
49997  0.089518  0.533103  0.211293  0.166087  149997
49998  0.085325  0.600829  0.165387  0.148459  149998
49999  0.091881  0.577574  0.201652  0.128893  149999

[50000 rows x 5 columns]

In [119]:
submission.to_csv("Final_submission.csv",index=False)